### ISSUE TITLE
Chevrons für Übersicht

### ISSUE THREAD

**Issue by crispin-kirchner** [crispin-kirchner/expenses#8]
Chevrons in den Übersichts-Boxen; wenn aufgeklappt ist gerne nach unten zeigend, am liebsten mit Rotations-Animation dazwischen

**Code-Stellen**
Overview.js: renderInnerRow() und renderOverviewRows()
Aufgeklapptes &lt;li&gt;s haben ein ul.collapse.show als Kind
Missglückter Versuch siehe im branche "features/cki/chevrons"

Zielbild in etwa so (die Blattknoten (im Beispiel "radiesli", "Hallerladen" und "Verbleinend") dürfen auch noch ein Chevron haben, das kann man dann später noch wegpacken; braucht je nachdem noch Anpassungen im render

![grafik](https://user-images.githubusercontent.com/6740795/175385678-441259f0-b78d-4261-b495-4b4e03f752bc.png)

**Comment by McMalloc** [comment]
Ich habe einen Vorschlag in den Branch gepusht. Für Blatteinträge, also Einträge ohne Kinder, habe ich erstmal den Middot genommen. Das kann in styles.scss:100 mit einem anderen Unicode-Codepoint geändert werden.
